import type { Champion, ChampionData, RiotChampionName } from "@src/types";

/** 2023/06/23 - 모든 챔피언 영문 이름 FIXME: 챔피언 계속 추가되는 거 생각하기 - by 1-blue */
export const riotChampionNames: RiotChampionName[] = [
  "Aatrox",
  "Ahri",
  "Akali",
  "Akshan",
  "Alistar",
  "Amumu",
  "Anivia",
  "Annie",
  "Aphelios",
  "Ashe",
  "AurelionSol",
  "Azir",
  "Bard",
  "Belveth",
  "Blitzcrank",
  "Brand",
  "Braum",
  "Caitlyn",
  "Camille",
  "Cassiopeia",
  "Chogath",
  "Corki",
  "Darius",
  "Diana",
  "Draven",
  "DrMundo",
  "Ekko",
  "Elise",
  "Evelynn",
  "Ezreal",
  "Fiddlesticks",
  "Fiora",
  "Fizz",
  "Galio",
  "Gangplank",
  "Garen",
  "Gnar",
  "Gragas",
  "Graves",
  "Gwen",
  "Hecarim",
  "Heimerdinger",
  "Illaoi",
  "Irelia",
  "Ivern",
  "Janna",
  "JarvanIV",
  "Jax",
  "Jayce",
  "Jhin",
  "Jinx",
  "Kaisa",
  "Kalista",
  "Karma",
  "Karthus",
  "Kassadin",
  "Katarina",
  "Kayle",
  "Kayn",
  "Kennen",
  "Khazix",
  "Kindred",
  "Kled",
  "KogMaw",
  "KSante",
  "Leblanc",
  "LeeSin",
  "Leona",
  "Lillia",
  "Lissandra",
  "Lucian",
  "Lulu",
  "Lux",
  "Malphite",
  "Malzahar",
  "Maokai",
  "MasterYi",
  "Milio",
  "MissFortune",
  "MonkeyKing",
  "Mordekaiser",
  "Morgana",
  "Nami",
  "Nasus",
  "Nautilus",
  "Neeko",
  "Nidalee",
  "Nilah",
  "Nocturne",
  "Nunu",
  "Olaf",
  "Orianna",
  "Ornn",
  "Pantheon",
  "Poppy",
  "Pyke",
  "Qiyana",
  "Quinn",
  "Rakan",
  "Rammus",
  "RekSai",
  "Rell",
  "Renata",
  "Renekton",
  "Rengar",
  "Riven",
  "Rumble",
  "Ryze",
  "Samira",
  "Sejuani",
  "Senna",
  "Seraphine",
  "Sett",
  "Shaco",
  "Shen",
  "Shyvana",
  "Singed",
  "Sion",
  "Sivir",
  "Skarner",
  "Sona",
  "Soraka",
  "Swain",
  "Sylas",
  "Syndra",
  "TahmKench",
  "Taliyah",
  "Talon",
  "Taric",
  "Teemo",
  "Thresh",
  "Tristana",
  "Trundle",
  "Tryndamere",
  "TwistedFate",
  "Twitch",
  "Udyr",
  "Urgot",
  "Varus",
  "Vayne",
  "Veigar",
  "Velkoz",
  "Vex",
  "Vi",
  "Viego",
  "Viktor",
  "Vladimir",
  "Volibear",
  "Warwick",
  "Xayah",
  "Xerath",
  "XinZhao",
  "Yasuo",
  "Yone",
  "Yorick",
  "Yuumi",
  "Zac",
  "Zed",
  "Zeri",
  "Ziggs",
  "Zilean",
  "Zoe",
  "Zyra",
];

/** 2023/06/25 - 이전/다음 챔피언 영문 이름 얻기 - by 1-blue */
export const getPrevAndNextRiotChampionNames = (name: RiotChampionName) => {
  const targetIndex = riotChampionNames.findIndex(
    (championName) => championName === name
  );

  let prevIndex = -1;
  let nextIndex = -1;

  // 처음이라면 끝으로
  if (targetIndex === 0) {
    prevIndex = riotChampionNames.length - 1;
  } else {
    prevIndex = targetIndex - 1;
  }

  // 끝이라면 처음으로
  if (targetIndex === riotChampionNames.length - 1) {
    nextIndex = 0;
  } else {
    nextIndex = targetIndex + 1;
  }

  return {
    prevChampionName: riotChampionNames[prevIndex],
    nextChampionName: riotChampionNames[nextIndex],
  };
};

/** 2023/06/26 - 특정 챔피언 상세 정보 테스트용 데이터 ( using StoryBook ) - by 1-blue */
export const getMocDetailChampion = (): Champion => ({
  id: "Poppy",
  name: "뽀삐",
  title: "망치의 수호자",
  allytips: [
    "강철의 외교관을 사용했을 때 던지는 방패는 보통 벽 옆에 떨어지므로 용감한 돌진 스킬을 연계하면 좋습니다.",
    "수호자의 심판은 힘을 모으지 않고도 사용할 수 있습니다. 1대1 상황에서 적에게 바로 수호자의 심판을 써서 밀어내 보세요.",
  ],
  enemytips: [
    "뽀삐는 굳건한 태세를 이용해 근처에서 돌진하는 적을 막을 수 있습니다.",
    "뽀삐가 망치를 돌리는 건 궁극기를 위해 힘을 모으고 있다는 뜻입니다.",
    "방패를 밟으면 뽀삐가 다시 줍지 못하도록 파괴할 수 있습니다.",
  ],
  stats: {
    hp: 610,
    hpperlevel: 104,
    mp: 280,
    mpperlevel: 40,
    movespeed: 345,
    armor: 38,
    armorperlevel: 4.7,
    spellblock: 32,
    spellblockperlevel: 2.05,
    attackrange: 125,
    hpregen: 8,
    hpregenperlevel: 0.8,
    mpregen: 7,
    mpregenperlevel: 0.7,
    crit: 0,
    critperlevel: 0,
    attackdamage: 64,
    attackdamageperlevel: 4,
    attackspeedperlevel: 2.5,
    attackspeed: 0.625,
  },
  info: {
    attack: 6,
    defense: 7,
    magic: 2,
    difficulty: 6,
  },
  skins: [
    {
      id: "78000",
      name: "default",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_0.jpg",
    },
    {
      id: "78001",
      name: "녹서스 뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_1.jpg",
    },
    {
      id: "78002",
      name: "롤리뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_2.jpg",
    },
    {
      id: "78003",
      name: "대장장이 뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_3.jpg",
    },
    {
      id: "78004",
      name: "봉제인형 뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_4.jpg",
    },
    {
      id: "78005",
      name: "전투 예복 뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_5.jpg",
    },
    {
      id: "78006",
      name: "붉은 망치 뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_6.jpg",
    },
    {
      id: "78007",
      name: "별 수호자 뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_7.jpg",
    },
    {
      id: "78014",
      name: "눈꽃사슴 뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_14.jpg",
    },
    {
      id: "78015",
      name: "마법공학 뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_15.jpg",
    },
    {
      id: "78016",
      name: "우주비행사 뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_16.jpg",
    },
    {
      id: "78024",
      name: "마녀 뽀삐",
      src: "http://ddragon.leagueoflegends.com/cdn/img/champion/loading/Poppy_24.jpg",
    },
  ],
  skills: [
    {
      type: "P",
      src: "http://ddragon.leagueoflegends.com/cdn/13.12.1/img/passive/Poppy_Passive.png",
      alt: "강철의 외교관 ( 뽀삐 패시브 )",
      title: "강철의 외교관",
      description:
        "뽀삐가 던진 방패가 대상을 맞히고 튕겨나갑니다. 뽀삐는 방패를 다시 주워 일시적인 보호막 효과를 얻을 수 있습니다.",
    },
    {
      type: "Q",
      src: "http://ddragon.leagueoflegends.com/cdn/13.12.1/img/spell/PoppyQ.png",
      alt: "망치 강타 ( 뽀삐 Q 스킬 )",
      title: "망치 강타",
      description:
        "뽀삐가 땅을 힘껏 내려쳐 <physicalDamage>(?)</physicalDamage>+최대 체력의 <physicalDamage>9%에 해당하는 물리 피해</physicalDamage>를 입히고 지대를 불안정하게 만듭니다. <br /><br />불안정한 지대는 적을 20/25/30/35/40% <status>둔화</status>시키고 1초 뒤 폭발하여 <physicalDamage>(?)</physicalDamage>+최대 체력의 <physicalDamage>9%에 해당하는 물리 피해</physicalDamage>를 입힙니다.(?)<br /><br />사거리: 430<br />소모값: 35/40/45/50/55<br />재사용 대기시간: 8/7/6/5/4",
    },
    {
      type: "W",
      src: "http://ddragon.leagueoflegends.com/cdn/13.12.1/img/spell/PoppyW.png",
      alt: "굳건한 태세 ( 뽀삐 W 스킬 )",
      title: "굳건한 태세",
      description:
        "<spellPassive>기본 지속 효과:</spellPassive> 뽀삐가 <scaleArmor>(?)의 방어력</scaleArmor>과 <scaleMR>(?)의 마법 저항력</scaleMR>을 추가로 얻습니다. 뽀삐의 체력이 (?)% 미만일 때는 효과가 두 배로 늘어납니다.<br /><br /><spellActive>사용 시:</spellActive> 뽀삐의 이동 속도가 <speed>40%</speed> 증가하고 역장을 둘러 2초 동안 주변에서 돌진하는 적을 막습니다. 가로막힌 적은 (?)초 동안 <status>이동 스킬을 사용할 수 없고</status> (?)% <status>둔화</status>되며 <magicDamage>(?)의 마법 피해</magicDamage>를 입습니다.(?)<br /><br />사거리: 400<br />소모값: 50<br />재사용 대기시간: 20/18/16/14/12",
    },
    {
      type: "E",
      src: "http://ddragon.leagueoflegends.com/cdn/13.12.1/img/spell/PoppyE.png",
      alt: "용감한 돌진 ( 뽀삐 E 스킬 )",
      title: "용감한 돌진",
      description:
        "뽀삐가 하나의 적에게 돌진해 <physicalDamage>(?)의 물리 피해</physicalDamage>를 입히고 앞으로 밀어냅니다. 적이 지형에 부딪히면 적이 1.6/1.7/1.8/1.9/2초 동안 <status>기절</status>하고 <physicalDamage>(?)의 추가 물리 피해</physicalDamage>를 입습니다.(?)<br /><br />사거리: 475<br />소모값: 70<br />재사용 대기시간: 14/13/12/11/10",
    },
    {
      type: "R",
      src: "http://ddragon.leagueoflegends.com/cdn/13.12.1/img/spell/PoppyR.png",
      alt: "수호자의 심판 ( 뽀삐 R 스킬 )",
      title: "수호자의 심판",
      description:
        "<charge>충전 시작 시:</charge> 뽀삐가 최대 (?)초 동안 망치를 충전하고 (?)% <status>둔화</status>됩니다.<br /><br /><release>사용 시:</release> 뽀삐가 지면에 강력한 일격을 날려 균열을 일으킵니다. 처음 적중한 적 챔피언과 주변 적은 <physicalDamage>(?)의 물리 피해</physicalDamage>를 입고 모두 <status>넥서스 쪽으로</status> <status>밀려나고</status> 공중에 떠오른 적은 대상으로 지정할 수 없게 됩니다. 균열의 길이와 적을 <status>밀어내는</status> 거리는 정신을 충전 시간에 비례합니다.<br /><br />충전하지 않고 바로 사용할 경우 <physicalDamage>(?)의 물리 피해</physicalDamage>를 입히고 적을 (?)초 동안 <status>공중으로</status> 띄워 올립니다.(?)<br /><br />사거리: 500<br />소모값: 100<br />재사용 대기시간: 140/120/100",
    },
  ],
});

/** 2023/06/26 - 특정 챔피언 상세 정보 테스트용 데이터 ( using StoryBook ) - by 1-blue */
export const getMocChampion = (): ChampionData => ({
  id: "Poppy",
  name: "뽀삐",
  title: "망치의 수호자",
  src: "http://ddragon.leagueoflegends.com/cdn/13.12.1/img/champion/Poppy.png",
  info: {
    attack: 6,
    defense: 7,
    magic: 2,
    difficulty: 6,
  },
  stats: {
    hp: 610,
    hpperlevel: 104,
    mp: 280,
    mpperlevel: 40,
    movespeed: 345,
    armor: 38,
    armorperlevel: 4.7,
    spellblock: 32,
    spellblockperlevel: 2.05,
    attackrange: 125,
    hpregen: 8,
    hpregenperlevel: 0.8,
    mpregen: 7,
    mpregenperlevel: 0.7,
    crit: 0,
    critperlevel: 0,
    attackdamage: 64,
    attackdamageperlevel: 4,
    attackspeedperlevel: 2.5,
    attackspeed: 0.625,
  },
  tags: ["Tank", "Fighter"],
});
